### ISSUE TITLE
StatsdClient always raise Exception in Connect()

### ISSUE THREAD

**Issue by AdamLeyshon** [so1n/aiostatsd#1]
When creating a new StatsdClient either through Context Manager or implicitly it always raises:

```python
  File "main.py", line 22, in main
    await client.connect()
  File "..\site-packages\aio_statsd\client.py", line 68, in connect
    raise ConnectionError(f"aiostatsd client already connected")
ConnectionError: aiostatsd client already connected
```

In Connect() it checks for
```python
async def connect(self) -> NoReturn:
    if self.is_closed:
        raise ConnectionError(f"aiostatsd client already connected")
```

But `self.is_closed` is always `true` according to Line 36 in the class ctor:
```python
class Client:
    def __init__(
        self,
        host: str = "localhost",
        port: int = 8125,
        protocol: ProtocolFlag = ProtocolFlag.udp,
        timeout: int = 0,
        debug: bool = False,
        close_timeout: int = 5,
        create_timeout: int = 5,
        max_len: int = 1000,
    ) -> NoReturn:
        
         ...

        self.is_closed: bool = True
```

This flag is only cleared during `Close` which can't be called because` _listen_future` is `None` and `Connect` clears it 5 lines down

**Comment by so1n** [comment]
> When creating a new StatsdClient either through Context Manager or implicitly it always raises:
> 
> ```python
>   File "main.py", line 22, in main
>     await client.connect()
>   File "..\site-packages\aio_statsd\client.py", line 68, in connect
>     raise ConnectionError(f"aiostatsd client already connected")
> ConnectionError: aiostatsd client already connected
> ```
> 
> In Connect() it checks for
> 
> ```python
> async def connect(self) -> NoReturn:
>     if self.is_closed:
>         raise ConnectionError(f"aiostatsd client already connected")
> ```
> 
> But `self.is_closed` is always `true` according to Line 36 in the class ctor:
> 
> ```python
> class Client:
>     def __init__(
>         self,
>         host: str = "localhost",
>         port: int = 8125,
>         protocol: ProtocolFlag = ProtocolFlag.udp,
>         timeout: int = 0,
>         debug: bool = False,
>         close_timeout: int = 5,
>         create_timeout: int = 5,
>         max_len: int = 1000,
>     ) -> NoReturn:
>         
>          ...
> 
>         self.is_closed: bool = True
> ```
> 
> This flag is only cleared during `Close` which can't be called because` _listen_future` is `None` and `Connect` clears it 5 lines down

A bug was submitted due to missing test cases, thank you for your feedback and fix. I will release a fix and add test cases later.

**Comment by AdamLeyshon** [comment]
No problem, glad I could help, thanks for the library. It's working well for my small smart home project.
