### ISSUE TITLE
Logging to the root logger

### ISSUE THREAD

**Issue by MerlijnWajer** [so1n/aiostatsd#4]
Hi, nice library. One thing, perhaps you could change the code so that it doesn't log to the python root logger, because that makes it hard to disable the logging messages from the internal library calls. See https://docs.python.org/3/howto/logging.html#library-config

I currently have to do something like this when using the library:

```
import logging
null = logging.getLogger('aio_statsd') # Make up our own name
null.addHandler(logging.NullHandler())
null.setLevel(logging.ERROR)

import aio_statsd
import aio_statsd.client
import aio_statsd.connection

aio_statsd.client.logging = null
aio_statsd.connection.logging = null

# Now, actually import the package
from aio_statsd import StatsdClient
```

Maybe I'm missing something, but I think it could be worth taking a look?

Thanks!

**Comment by so1n** [comment]
> Hi, nice library. One thing, perhaps you could change the code so that it doesn't log to the python root logger, because that makes it hard to disable the logging messages from the internal library calls. See https://docs.python.org/3/howto/logging.html#library-config
> 
> I currently have to do something like this when using the library:
> 
> ```
> import logging
> null = logging.getLogger('aio_statsd') # Make up our own name
> null.addHandler(logging.NullHandler())
> null.setLevel(logging.ERROR)
> 
> import aio_statsd
> import aio_statsd.client
> import aio_statsd.connection
> 
> aio_statsd.client.logging = null
> aio_statsd.connection.logging = null
> 
> # Now, actually import the package
> from aio_statsd import StatsdClient
> ```
> 
> Maybe I'm missing something, but I think it could be worth taking a look?
> 
> Thanks!


Thank you for your feedback, I have now modified and released version 0.2.8 based on your feedback, you can upgrade to version 0.2.8 and run it according to the code below

```Python
import logging


for module_name in [
    "aio_statsd.client",
    "aio_statsd.connection",
    "aio_statsd.transport_layer_protocol",
]:
    logging.getLogger(module_name).setLevel(logging.ERROR)
    logging.getLogger(module_name).addHandler(logging.NullHandler())


from aio_statsd import StatsdClient
```
