### ISSUE TITLE
Add py.typed

### ISSUE THREAD

**Issue by daxartio** [so1n/aiostatsd#6]
Please add py.typed file

```
error: Skipping analyzing "aio_statsd": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by so1n** [comment]
Hi! @daxartio .This library does not require the creation of a py.typed file, so please check that you are using tools such as mypy correctly!

**Comment by daxartio** [comment]
py.typed is needed to say mypy that the package has type annotations. 

> The py. typed file is a marker file that indicates to type checkers like mypy that your package comes with type annotations. Without this file, the type checker won't use the type hints provided by your package, leading to potential type errors.

**Comment by so1n** [comment]
All methods and functions of aiostatsd use Type annotations, so there is no need to write a separate py.typed file.Please check aiostatsd is installed in mypy's runtime environment.


> py.typed is needed to say mypy that the package has type annotations.
> 
> > The py. typed file is a marker file that indicates to type checkers like mypy that your package comes with type annotations. Without this file, the type checker won't use the type hints provided by your package, leading to potential type errors.

**Comment by daxartio** [comment]
https://peps.python.org/pep-0561/#packaging-type-information
As an example, you can see in fastapi repo this file https://github.com/tiangolo/fastapi/tree/master/fastapi

**Comment by so1n** [comment]
Thanks for the documentation and examples, I'll fix this over the weekend! @daxartio
